apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mypubsub1
  namespace: default
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    value: Endpoint=sb://REDACTED_SERVICEBUS_NAMESPACE.servicebus.windows.net/;SharedAccessKeyName=policy1;SharedAccessKey=REDACTED_KEY;EntityPath=mytopic1