apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mybinding2
  namespace: default
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
  - name: storageAccount
    value: REDACTED_STORAGE_ACCOUNT_NAME
  - name: storageAccessKey
    value: REDACTED_STORAGE_ACCOUNT_KEY
  - name: queue
    value: mystorequeue1
  - name: ttlInSeconds
    value: 600